In [2]:
l1 = [10,20,30]
l2 = [30,40,50]
l1+l2

[10, 20, 30, 30, 40, 50]

In [3]:
# memory 
import numpy as np

In [4]:
l1 = [1,2,3]
x = np.array(object=l1)
print(x)

[1 2 3]


In [5]:
type(x)

numpy.ndarray

In [6]:
x = np.array(object=[[1,2,3],[23,4,5]])
print(x)

[[ 1  2  3]
 [23  4  5]]


In [7]:
x[1,1] # indexing

4

In [8]:
# metadata/attribute
x.shape # returns the shape of an array

(2, 3)

In [9]:
x.dtype # data type of an array

dtype('int64')

In [10]:
x.ndim # number of dimensions of an array

2

In [11]:
x = np.array(object=[[1,2,3],[23,"4","5"]])
print(x) # all the values will be converted to string

[['1' '2' '3']
 ['23' '4' '5']]


int < float < complex < str

In [12]:
np.arange(10, 20) # return the values filled between start and stop
# start is included, stop is excluded

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
np.zeros(shape=(4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones(shape=(4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.linspace(start=1,stop=5,num=10) # generate the array with required equidistant elements from start to stop

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [16]:
arr = np.linspace(start=1,stop=5,num=10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [17]:
arr.shape # metadata / attribute

(10,)

In [18]:
arr.ndim

1

In [19]:
arr1 = arr.reshape(2,5)

In [20]:
arr1

array([[1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778],
       [3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ]])

In [21]:
arr1.shape

(2, 5)

In [22]:
arr1 + arr1

array([[ 2.        ,  2.88888889,  3.77777778,  4.66666667,  5.55555556],
       [ 6.44444444,  7.33333333,  8.22222222,  9.11111111, 10.        ]])

In [23]:
arr1 * arr1

array([[ 1.        ,  2.08641975,  3.56790123,  5.44444444,  7.71604938],
       [10.38271605, 13.44444444, 16.90123457, 20.75308642, 25.        ]])

In [24]:
arr1 / arr1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
x = np.ones(shape=(2,3,4))

In [26]:
x.dtype

dtype('float64')

In [27]:
x = np.array(['a','b'])

In [28]:
x*x

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U1'), dtype('<U1')) -> None

In [ ]:
l2 = [20.2, 35.6, 45.98, 50.25]
x = np.array(l2, dtype='int') # no rounding
x

In [ ]:
#64 bit data is used
x.dtype

In [ ]:
x = np.array(l2, dtype=np.int8) # no rounding
x

In [ ]:
x[0] = "hello"

In [ ]:
x[0] = 12.25

In [ ]:
x

In [ ]:
np.ones(shape=(2,3,2))

In [ ]:
# Indexing & Slicing

In [ ]:
# random module
x = np.random.randint(low=10,high=100,size=(4,3)) # numpy array filled with random integers with mentioned range and shape
x

In [ ]:
#indexing
x[2,2]

In [ ]:
# Slicing
# start is included and stop is excluded
x = np.random.randint(low=10,high=100,size=(6,7)) # numpy array filled with random integers with mentioned range and shape
x

In [ ]:
x[3:5,5:7]

In [ ]:
x[5,10]

In [ ]:
x[3:5,5:10] # no error

In [ ]:
x[3:5,5:]

In [ ]:
x[2:5,1:3]

In [ ]:
x[2:5]

In [ ]:
x[2:5,2:5]

# Pandas Library

In [1]:
import pandas as pd

In [2]:
s1 = pd.Series(data=[10,20,30,40], index=['a','b','c','d'], name="my_series", dtype='float')
s1 # A pandas series can contain the values of same data type

a    10.0
b    20.0
c    30.0
d    40.0
Name: my_series, dtype: float64

In [3]:
s1.name # return name

'my_series'

In [4]:
s1.values

array([10., 20., 30., 40.])

In [5]:
s1.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [6]:
s1 = pd.Series(data=[10,20,30,40], name="my_series", dtype='float')
s1 # A pandas series can contain the values of same data type

0    10.0
1    20.0
2    30.0
3    40.0
Name: my_series, dtype: float64

In [7]:
import numpy as np
arr = np.random.randint(0,100,(5,3))
arr

array([[ 4, 73, 55],
       [32, 92, 45],
       [80, 95, 14],
       [54, 75, 10],
       [57,  7, 37]])

In [8]:
df = pd.DataFrame(data=arr, index = list('abcde'), columns=list('xyz'))
df

x   y   z
a   4  73  55
b  32  92  45
c  80  95  14
d  54  75  10
e  57   7  37

In [9]:
df.dtypes

x    int64
y    int64
z    int64
dtype: object

In [10]:
df.shape

(5, 3)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, a to e
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   x       5 non-null      int64
 1   y       5 non-null      int64
 2   z       5 non-null      int64
dtypes: int64(3)
memory usage: 160.0+ bytes


In [12]:
df.values

array([[ 4, 73, 55],
       [32, 92, 45],
       [80, 95, 14],
       [54, 75, 10],
       [57,  7, 37]])

In [13]:
type(s1)

pandas.core.series.Series

In [14]:
type(df)

pandas.core.frame.DataFrame

In [15]:
# selecting a columns
ex = df['x']
ex

a     4
b    32
c    80
d    54
e    57
Name: x, dtype: int64

In [16]:
type(ex)

pandas.core.series.Series

# Data Wrangling with Pandas DataFrame

In [17]:
df = pd.read_csv("IPL IMB381IPL2013.csv")
df

Sl.NO.   PLAYER NAME  AGE COUNTRY   TEAM PLAYING ROLE  T-RUNS  T-WKTS  \
0         1   Abdulla, YA    2      SA   KXIP   Allrounder       0       0   
1         2  Abdur Razzak    2     BAN    RCB       Bowler     214      18   
2         3   Agarkar, AB    2     IND    KKR       Bowler     571      58   
3         4     Ashwin, R    1     IND    CSK       Bowler     284      31   
4         5  Badrinath, S    2     IND    CSK      Batsman      63       0   
..      ...           ...  ...     ...    ...          ...     ...     ...   
125     126     Yadav, AS    2     IND     DC      Batsman       0       0   
126     127   Younis Khan    2     PAK     RR      Batsman    6398       7   
127     128  Yuvraj Singh    2     IND  KXIP+      Batsman    1775       9   
128     129   Zaheer Khan    2     IND    MI+       Bowler    1114     288   
129     130    Zoysa, DNT    2      SL     DC       Bowler     288      64   

     ODI-RUNS-S  ODI-SR-B  ...    SR-B  SIXERS  RUNS-C  WKTS  AVE-BL   ECON  \
0             0      0.00  ...    0.00       0     307    15   20.47   8.90   
1           657     71.41  ...    0.00       0      29     0    0.00  14.50   
2          1269     80.62  ...  121.01       5    1059    29   36.52   8.81   
3           241     84.56  ...   76.32       0    1125    49   22.96   6.23   
4            79     45.93  ...  120.71      28       0     0    0.00   0.00   
..          ...       ...  ...     ...     ...     ...   ...     ...    ...   
125           0      0.00  ...  125.64       2       0     0    0.00   0.00   
126        6814     75.78  ...   42.85       0       0     0    0.00   0.00   
127        8051     87.58  ...  131.88      67     569    23   24.74   7.02   
128         790     73.55  ...   91.67       1    1783    65   27.43   7.75   
129         343     95.81  ...  122.22       0      99     2   49.50   9.00   

     SR-BL  AUCTION YEAR  BASE PRICE  SOLD PRICE  
0    13.93          2009       50000       50000  
1     0.00          2008       50000       50000  
2    24.90          2008      200000      350000  
3    22.14          2011      100000      850000  
4     0.00          2011      100000      800000  
..     ...           ...         ...         ...  
125   0.00          2010       50000      750000  
126   0.00          2008      225000      225000  
127  21.13          2011      400000     1800000  
128  21.26          2008      200000      450000  
129  33.00          2008      100000      110000  

[130 rows x 26 columns]

In [18]:
df.dtypes

Sl.NO.             int64
PLAYER NAME       object
AGE                int64
COUNTRY           object
TEAM              object
PLAYING ROLE      object
T-RUNS             int64
T-WKTS             int64
ODI-RUNS-S         int64
ODI-SR-B         float64
ODI-WKTS           int64
ODI-SR-BL        float64
CAPTAINCY EXP      int64
RUNS-S             int64
HS                 int64
AVE              float64
SR-B             float64
SIXERS             int64
RUNS-C             int64
WKTS               int64
AVE-BL           float64
ECON             float64
SR-BL            float64
AUCTION YEAR       int64
BASE PRICE         int64
SOLD PRICE         int64
dtype: object

In [19]:
df.values # arrays

array([[1, 'Abdulla, YA', 2, ..., 2009, 50000, 50000],
       [2, 'Abdur Razzak', 2, ..., 2008, 50000, 50000],
       [3, 'Agarkar, AB', 2, ..., 2008, 200000, 350000],
       ...,
       [128, 'Yuvraj Singh', 2, ..., 2011, 400000, 1800000],
       [129, 'Zaheer Khan', 2, ..., 2008, 200000, 450000],
       [130, 'Zoysa, DNT', 2, ..., 2008, 100000, 110000]], dtype=object)

In [20]:
df

Sl.NO.   PLAYER NAME  AGE COUNTRY   TEAM PLAYING ROLE  T-RUNS  T-WKTS  \
0         1   Abdulla, YA    2      SA   KXIP   Allrounder       0       0   
1         2  Abdur Razzak    2     BAN    RCB       Bowler     214      18   
2         3   Agarkar, AB    2     IND    KKR       Bowler     571      58   
3         4     Ashwin, R    1     IND    CSK       Bowler     284      31   
4         5  Badrinath, S    2     IND    CSK      Batsman      63       0   
..      ...           ...  ...     ...    ...          ...     ...     ...   
125     126     Yadav, AS    2     IND     DC      Batsman       0       0   
126     127   Younis Khan    2     PAK     RR      Batsman    6398       7   
127     128  Yuvraj Singh    2     IND  KXIP+      Batsman    1775       9   
128     129   Zaheer Khan    2     IND    MI+       Bowler    1114     288   
129     130    Zoysa, DNT    2      SL     DC       Bowler     288      64   

     ODI-RUNS-S  ODI-SR-B  ...    SR-B  SIXERS  RUNS-C  WKTS  AVE-BL   ECON  \
0             0      0.00  ...    0.00       0     307    15   20.47   8.90   
1           657     71.41  ...    0.00       0      29     0    0.00  14.50   
2          1269     80.62  ...  121.01       5    1059    29   36.52   8.81   
3           241     84.56  ...   76.32       0    1125    49   22.96   6.23   
4            79     45.93  ...  120.71      28       0     0    0.00   0.00   
..          ...       ...  ...     ...     ...     ...   ...     ...    ...   
125           0      0.00  ...  125.64       2       0     0    0.00   0.00   
126        6814     75.78  ...   42.85       0       0     0    0.00   0.00   
127        8051     87.58  ...  131.88      67     569    23   24.74   7.02   
128         790     73.55  ...   91.67       1    1783    65   27.43   7.75   
129         343     95.81  ...  122.22       0      99     2   49.50   9.00   

     SR-BL  AUCTION YEAR  BASE PRICE  SOLD PRICE  
0    13.93          2009       50000       50000  
1     0.00          2008       50000       50000  
2    24.90          2008      200000      350000  
3    22.14          2011      100000      850000  
4     0.00          2011      100000      800000  
..     ...           ...         ...         ...  
125   0.00          2010       50000      750000  
126   0.00          2008      225000      225000  
127  21.13          2011      400000     1800000  
128  21.26          2008      200000      450000  
129  33.00          2008      100000      110000  

[130 rows x 26 columns]

In [21]:
df.head(n=10) # first 5 rows of dataset

Sl.NO.    PLAYER NAME  AGE COUNTRY  TEAM PLAYING ROLE  T-RUNS  T-WKTS  \
0       1    Abdulla, YA    2      SA  KXIP   Allrounder       0       0   
1       2   Abdur Razzak    2     BAN   RCB       Bowler     214      18   
2       3    Agarkar, AB    2     IND   KKR       Bowler     571      58   
3       4      Ashwin, R    1     IND   CSK       Bowler     284      31   
4       5   Badrinath, S    2     IND   CSK      Batsman      63       0   
5       6     Bailey, GJ    2     AUS   CSK      Batsman       0       0   
6       7      Balaji, L    2     IND  CSK+       Bowler      51      27   
7       8  Bollinger, DE    2     AUS   CSK       Bowler      54      50   
8       9       Botha, J    2      SA    RR   Allrounder      83      17   
9      10    Boucher, MV    2      SA  RCB+    W. Keeper    5515       1   

   ODI-RUNS-S  ODI-SR-B  ...    SR-B  SIXERS  RUNS-C  WKTS  AVE-BL   ECON  \
0           0      0.00  ...    0.00       0     307    15   20.47   8.90   
1         657     71.41  ...    0.00       0      29     0    0.00  14.50   
2        1269     80.62  ...  121.01       5    1059    29   36.52   8.81   
3         241     84.56  ...   76.32       0    1125    49   22.96   6.23   
4          79     45.93  ...  120.71      28       0     0    0.00   0.00   
5         172     72.26  ...   95.45       0       0     0    0.00   0.00   
6         120     78.94  ...   72.22       1    1342    52   25.81   7.98   
7          50     92.59  ...  165.88       1     693    37   18.73   7.22   
8         609     85.77  ...  114.73       3     610    19   32.11   6.85   
9        4686     84.76  ...  127.51      13       0     0    0.00   0.00   

   SR-BL  AUCTION YEAR  BASE PRICE  SOLD PRICE  
0  13.93          2009       50000       50000  
1   0.00          2008       50000       50000  
2  24.90          2008      200000      350000  
3  22.14          2011      100000      850000  
4   0.00          2011      100000      800000  
5   0.00          2009       50000       50000  
6  19.40          2011      100000      500000  
7  15.57          2011      200000      700000  
8  28.11          2011      200000      950000  
9   0.00          2008      200000      450000  

[10 rows x 26 columns]

In [22]:
df.tail(n=10) # last 5 rows of dataset

Sl.NO.     PLAYER NAME  AGE COUNTRY   TEAM PLAYING ROLE  T-RUNS  T-WKTS  \
120     121     Vettori, DL    2      NZ    DD+   Allrounder    4486     359   
121     122  Vinay Kumar, R    2     IND   RCB+       Bowler      11       1   
122     123       Warne, SK    3     AUS     RR       Bowler    3154     708   
123     124      Warner, DA    1     AUS     DD      Batsman     483       2   
124     125       White, CL    2     AUS   RCB+      Batsman     146       5   
125     126       Yadav, AS    2     IND     DC      Batsman       0       0   
126     127     Younis Khan    2     PAK     RR      Batsman    6398       7   
127     128    Yuvraj Singh    2     IND  KXIP+      Batsman    1775       9   
128     129     Zaheer Khan    2     IND    MI+       Bowler    1114     288   
129     130      Zoysa, DNT    2      SL     DC       Bowler     288      64   

     ODI-RUNS-S  ODI-SR-B  ...    SR-B  SIXERS  RUNS-C  WKTS  AVE-BL   ECON  \
120        2105     81.93  ...  107.08       2     878    28   31.36   6.81   
121          43     43.87  ...  104.83       5    1664    61   27.28   8.24   
122        1018     72.04  ...   92.52       6    1447    57   25.39   7.27   
123         876     85.79  ...  135.76      44       0     0    0.00   0.00   
124        2037     80.48  ...  132.09      29      70     0    0.00  14.00   
125           0      0.00  ...  125.64       2       0     0    0.00   0.00   
126        6814     75.78  ...   42.85       0       0     0    0.00   0.00   
127        8051     87.58  ...  131.88      67     569    23   24.74   7.02   
128         790     73.55  ...   91.67       1    1783    65   27.43   7.75   
129         343     95.81  ...  122.22       0      99     2   49.50   9.00   

     SR-BL  AUCTION YEAR  BASE PRICE  SOLD PRICE  
120  27.75          2008      250000      625000  
121  19.87          2011      100000      475000  
122  20.95          2008      450000      450000  
123   0.00          2011      200000      750000  
124   0.00          2008      100000      500000  
125   0.00          2010       50000      750000  
126   0.00          2008      225000      225000  
127  21.13          2011      400000     1800000  
128  21.26          2008      200000      450000  
129  33.00          2008      100000      110000  

[10 rows x 26 columns]

In [23]:
#select the Player name list from data frame
df['PLAYER NAME']

0       Abdulla, YA
1      Abdur Razzak
2       Agarkar, AB
3         Ashwin, R
4      Badrinath, S
           ...     
125       Yadav, AS
126     Younis Khan
127    Yuvraj Singh
128     Zaheer Khan
129      Zoysa, DNT
Name: PLAYER NAME, Length: 130, dtype: object

In [24]:
# select multiple columns
# Select player name as well as Country

In [25]:
df[["PLAYER NAME","COUNTRY"]] # specify multiple column names inside the list

PLAYER NAME COUNTRY
0     Abdulla, YA      SA
1    Abdur Razzak     BAN
2     Agarkar, AB     IND
3       Ashwin, R     IND
4    Badrinath, S     IND
..            ...     ...
125     Yadav, AS     IND
126   Younis Khan     PAK
127  Yuvraj Singh     IND
128   Zaheer Khan     IND
129    Zoysa, DNT      SL

[130 rows x 2 columns]

## Slicing and Indexing

In [26]:
# index position
# index labels
df.head()

Sl.NO.   PLAYER NAME  AGE COUNTRY  TEAM PLAYING ROLE  T-RUNS  T-WKTS  \
0       1   Abdulla, YA    2      SA  KXIP   Allrounder       0       0   
1       2  Abdur Razzak    2     BAN   RCB       Bowler     214      18   
2       3   Agarkar, AB    2     IND   KKR       Bowler     571      58   
3       4     Ashwin, R    1     IND   CSK       Bowler     284      31   
4       5  Badrinath, S    2     IND   CSK      Batsman      63       0   

   ODI-RUNS-S  ODI-SR-B  ...    SR-B  SIXERS  RUNS-C  WKTS  AVE-BL   ECON  \
0           0      0.00  ...    0.00       0     307    15   20.47   8.90   
1         657     71.41  ...    0.00       0      29     0    0.00  14.50   
2        1269     80.62  ...  121.01       5    1059    29   36.52   8.81   
3         241     84.56  ...   76.32       0    1125    49   22.96   6.23   
4          79     45.93  ...  120.71      28       0     0    0.00   0.00   

   SR-BL  AUCTION YEAR  BASE PRICE  SOLD PRICE  
0  13.93          2009       50000       50000  
1   0.00          2008       50000       50000  
2  24.90          2008      200000      350000  
3  22.14          2011      100000      850000  
4   0.00          2011      100000      800000  

[5 rows x 26 columns]

In [27]:
# iloc --> index position
df.iloc[0,1]

'Abdulla, YA'

In [28]:
#loc --> index label
df.loc[0,"PLAYER NAME"]

'Abdulla, YA'

In [29]:
#slicing
df.iloc[0:3,0:5] # end is excluded

Sl.NO.   PLAYER NAME  AGE COUNTRY  TEAM
0       1   Abdulla, YA    2      SA  KXIP
1       2  Abdur Razzak    2     BAN   RCB
2       3   Agarkar, AB    2     IND   KKR

In [30]:
#slicing - index label
df.loc[0:3,"PLAYER NAME": "PLAYING ROLE"] # end is included

PLAYER NAME  AGE COUNTRY  TEAM PLAYING ROLE
0   Abdulla, YA    2      SA  KXIP   Allrounder
1  Abdur Razzak    2     BAN   RCB       Bowler
2   Agarkar, AB    2     IND   KKR       Bowler
3     Ashwin, R    1     IND   CSK       Bowler

In [31]:
output = df[["PLAYER NAME","COUNTRY"]]

In [32]:
output

PLAYER NAME COUNTRY
0     Abdulla, YA      SA
1    Abdur Razzak     BAN
2     Agarkar, AB     IND
3       Ashwin, R     IND
4    Badrinath, S     IND
..            ...     ...
125     Yadav, AS     IND
126   Younis Khan     PAK
127  Yuvraj Singh     IND
128   Zaheer Khan     IND
129    Zoysa, DNT      SL

[130 rows x 2 columns]

In [33]:
set(output['COUNTRY']) # unique values of column

{'AUS', 'BAN', 'ENG', 'IND', 'NZ', 'PAK', 'SA', 'SL', 'WI', 'ZIM'}

In [34]:
output['COUNTRY'].unique() # alternate way

array(['SA', 'BAN', 'IND', 'AUS', 'WI', 'SL', 'NZ', 'ENG', 'PAK', 'ZIM'],
      dtype=object)

In [35]:
output['COUNTRY'].nunique() # number of unique

10

In [36]:
# I want to return as how many players belong to each country
output['COUNTRY']

0       SA
1      BAN
2      IND
3      IND
4      IND
      ... 
125    IND
126    PAK
127    IND
128    IND
129     SL
Name: COUNTRY, Length: 130, dtype: object

In [37]:
output['COUNTRY'].value_counts()

IND    53
AUS    22
SA     16
SL     12
PAK     9
NZ      7
WI      6
ENG     3
BAN     1
ZIM     1
Name: COUNTRY, dtype: int64

In [38]:
df.columns

Index(['Sl.NO.', 'PLAYER NAME', 'AGE', 'COUNTRY', 'TEAM', 'PLAYING ROLE',
       'T-RUNS', 'T-WKTS', 'ODI-RUNS-S', 'ODI-SR-B', 'ODI-WKTS', 'ODI-SR-BL',
       'CAPTAINCY EXP', 'RUNS-S', 'HS', 'AVE', 'SR-B', 'SIXERS', 'RUNS-C',
       'WKTS', 'AVE-BL', 'ECON', 'SR-BL', 'AUCTION YEAR', 'BASE PRICE',
       'SOLD PRICE'],
      dtype='object')

In [39]:
df1 = df[['PLAYER NAME','SOLD PRICE']]
df1

PLAYER NAME  SOLD PRICE
0     Abdulla, YA       50000
1    Abdur Razzak       50000
2     Agarkar, AB      350000
3       Ashwin, R      850000
4    Badrinath, S      800000
..            ...         ...
125     Yadav, AS      750000
126   Younis Khan      225000
127  Yuvraj Singh     1800000
128   Zaheer Khan      450000
129    Zoysa, DNT      110000

[130 rows x 2 columns]

In [40]:
df1.sort_values(by="SOLD PRICE", ascending=False).head(10) # Top 10 highest Sold price of players

PLAYER NAME  SOLD PRICE
93       Sehwag, V     1800000
127   Yuvraj Singh     1800000
50        Kohli, V     1800000
111  Tendulkar, SR     1800000
113     Tiwary, SS     1600000
83   Pietersen, KP     1550000
23     Flintoff, A     1550000
15       Dhoni, MS     1500000
108     Symonds, A     1350000
110   Taylor, LRPL     1000000

In [41]:
df.columns

Index(['Sl.NO.', 'PLAYER NAME', 'AGE', 'COUNTRY', 'TEAM', 'PLAYING ROLE',
       'T-RUNS', 'T-WKTS', 'ODI-RUNS-S', 'ODI-SR-B', 'ODI-WKTS', 'ODI-SR-BL',
       'CAPTAINCY EXP', 'RUNS-S', 'HS', 'AVE', 'SR-B', 'SIXERS', 'RUNS-C',
       'WKTS', 'AVE-BL', 'ECON', 'SR-BL', 'AUCTION YEAR', 'BASE PRICE',
       'SOLD PRICE'],
      dtype='object')

In [42]:
# PREMIUM = SOLD PRICE - BASE PRICE
df['PREMIUM'] = df["SOLD PRICE"] - df["BASE PRICE"] # data transformation

In [43]:
df.head()

Sl.NO.   PLAYER NAME  AGE COUNTRY  TEAM PLAYING ROLE  T-RUNS  T-WKTS  \
0       1   Abdulla, YA    2      SA  KXIP   Allrounder       0       0   
1       2  Abdur Razzak    2     BAN   RCB       Bowler     214      18   
2       3   Agarkar, AB    2     IND   KKR       Bowler     571      58   
3       4     Ashwin, R    1     IND   CSK       Bowler     284      31   
4       5  Badrinath, S    2     IND   CSK      Batsman      63       0   

   ODI-RUNS-S  ODI-SR-B  ...  SIXERS  RUNS-C  WKTS  AVE-BL   ECON  SR-BL  \
0           0      0.00  ...       0     307    15   20.47   8.90  13.93   
1         657     71.41  ...       0      29     0    0.00  14.50   0.00   
2        1269     80.62  ...       5    1059    29   36.52   8.81  24.90   
3         241     84.56  ...       0    1125    49   22.96   6.23  22.14   
4          79     45.93  ...      28       0     0    0.00   0.00   0.00   

   AUCTION YEAR  BASE PRICE  SOLD PRICE  PREMIUM  
0          2009       50000       50000        0  
1          2008       50000       50000        0  
2          2008      200000      350000   150000  
3          2011      100000      850000   750000  
4          2011      100000      800000   700000  

[5 rows x 27 columns]

In [44]:
df.sort_values(by="PREMIUM", ascending=False).head(10)

Sl.NO.    PLAYER NAME  AGE COUNTRY   TEAM PLAYING ROLE  T-RUNS  T-WKTS  \
50       51       Kohli, V    1     IND    RCB      Batsman     491       0   
113     114     Tiwary, SS    1     IND    MI+      Batsman       0       0   
127     128   Yuvraj Singh    2     IND  KXIP+      Batsman    1775       9   
111     112  Tendulkar, SR    3     IND     MI      Batsman   15470      45   
93       94      Sehwag, V    2     IND     DD      Batsman    8178      40   
108     109     Symonds, A    3     AUS    DC+   Allrounder    1462      24   
15       16      Dhoni, MS    2     IND    CSK    W. Keeper    3509       0   
39       40     Jadeja, RA    1     IND    RR+   Allrounder       0       0   
95       96      Sharma, I    1     IND   KKR+       Bowler     432     133   
3         4      Ashwin, R    1     IND    CSK       Bowler     284      31   

     ODI-RUNS-S  ODI-SR-B  ...  SIXERS  RUNS-C  WKTS  AVE-BL   ECON  SR-BL  \
50         3590     86.31  ...      49     345     4   86.25   8.84  58.50   
113          49     87.50  ...      32       0     0    0.00   0.00   0.00   
127        8051     87.58  ...      67     569    23   24.74   7.02  21.13   
111       18426     86.23  ...      24      58     0    0.00   9.67   0.00   
93         8090    104.68  ...      79     226     6   37.67  10.56  21.67   
108        5088     92.44  ...      41     674    20   33.70   7.70  26.35   
15         6773     88.19  ...      64       0     0    0.00   0.00   0.00   
39          860     78.61  ...      35     750    26   28.85   7.33  23.65   
95           47     34.05  ...       1    1176    36   32.67   7.63  23.61   
3           241     84.56  ...       0    1125    49   22.96   6.23  22.14   

     AUCTION YEAR  BASE PRICE  SOLD PRICE  PREMIUM  
50           2011      150000     1800000  1650000  
113          2011      100000     1600000  1500000  
127          2011      400000     1800000  1400000  
111          2011      400000     1800000  1400000  
93           2011      400000     1800000  1400000  
108          2008      250000     1350000  1100000  
15           2008      400000     1500000  1100000  
39           2011      100000      950000   850000  
95           2008      150000      950000   800000  
3            2011      100000      850000   750000  

[10 rows x 27 columns]

In [45]:
df1

PLAYER NAME  SOLD PRICE
0     Abdulla, YA       50000
1    Abdur Razzak       50000
2     Agarkar, AB      350000
3       Ashwin, R      850000
4    Badrinath, S      800000
..            ...         ...
125     Yadav, AS      750000
126   Younis Khan      225000
127  Yuvraj Singh     1800000
128   Zaheer Khan      450000
129    Zoysa, DNT      110000

[130 rows x 2 columns]

In [46]:
df1 = df1[['SOLD PRICE',"PLAYER NAME"]]
df1

SOLD PRICE   PLAYER NAME
0         50000   Abdulla, YA
1         50000  Abdur Razzak
2        350000   Agarkar, AB
3        850000     Ashwin, R
4        800000  Badrinath, S
..          ...           ...
125      750000     Yadav, AS
126      225000   Younis Khan
127     1800000  Yuvraj Singh
128      450000   Zaheer Khan
129      110000    Zoysa, DNT

[130 rows x 2 columns]

In [47]:
df["PLAYER NAME"]

0       Abdulla, YA
1      Abdur Razzak
2       Agarkar, AB
3         Ashwin, R
4      Badrinath, S
           ...     
125       Yadav, AS
126     Younis Khan
127    Yuvraj Singh
128     Zaheer Khan
129      Zoysa, DNT
Name: PLAYER NAME, Length: 130, dtype: object

In [48]:
df[["PLAYER NAME","COUNTRY"]]

PLAYER NAME COUNTRY
0     Abdulla, YA      SA
1    Abdur Razzak     BAN
2     Agarkar, AB     IND
3       Ashwin, R     IND
4    Badrinath, S     IND
..            ...     ...
125     Yadav, AS     IND
126   Younis Khan     PAK
127  Yuvraj Singh     IND
128   Zaheer Khan     IND
129    Zoysa, DNT      SL

[130 rows x 2 columns]

In [49]:
# select a column as index --> return as series
# select a column as a list in the index operator - dataframe
df['PREMIUM'] # series

0            0
1            0
2       150000
3       750000
4       700000
        ...   
125     700000
126          0
127    1400000
128     250000
129      10000
Name: PREMIUM, Length: 130, dtype: int64

In [50]:
df[['PREMIUM']] # dataframe

PREMIUM
0          0
1          0
2     150000
3     750000
4     700000
..       ...
125   700000
126        0
127  1400000
128   250000
129    10000

[130 rows x 1 columns]

In [51]:
# Groupby
# apply
# Fixing the errors
# merging/Concatenation
# take care of missing values
# describe the statistical properties of the dataframe

In [52]:
# Boolen Indexing

In [53]:
df['COUNTRY'] == "IND" #. boolean

0      False
1      False
2       True
3       True
4       True
       ...  
125     True
126    False
127     True
128     True
129    False
Name: COUNTRY, Length: 130, dtype: bool

In [54]:
df[df['COUNTRY'] == "IND"]

Sl.NO.       PLAYER NAME  AGE COUNTRY   TEAM PLAYING ROLE  T-RUNS  \
2         3       Agarkar, AB    2     IND    KKR       Bowler     571   
3         4         Ashwin, R    1     IND    CSK       Bowler     284   
4         5      Badrinath, S    2     IND    CSK      Batsman      63   
6         7         Balaji, L    2     IND   CSK+       Bowler      51   
12       13        Chawla, PP    1     IND   KXIP   Allrounder       5   
14       15         Dhawan, S    2     IND    MI+      Batsman       0   
15       16         Dhoni, MS    2     IND    CSK    W. Keeper    3509   
17       18         Dinda, AB    2     IND   KKR+       Bowler       0   
18       19        Dravid, RS    3     IND   RCB+      Batsman   13288   
24       25        Gambhir, G    2     IND    DD+      Batsman    3712   
25       26       Ganguly, SC    3     IND   KKR+      Batsman    7212   
29       30          Gony, MS    2     IND   CSK+       Bowler       0   
30       31   Harbhajan Singh    2     IND     MI       Bowler    2164   
39       40        Jadeja, RA    1     IND    RR+   Allrounder       0   
40       41         Jaffer, W    2     IND    RCB   Allrounder    1944   
43       44           Kaif, M    2     IND    RR+      Batsman     624   
46       47       Kamran Khan    1     IND    RR+       Bowler       0   
47       48       Karthik, KD    2     IND    DD+    W. Keeper    1000   
48       49         Kartik, M    2     IND   KKR+       Bowler      88   
50       51          Kohli, V    1     IND    RCB      Batsman     491   
51       52          Kumar, P    1     IND   RCB+       Bowler     149   
52       53         Kumble, A    3     IND    RCB       Bowler    2506   
54       55       Laxman, VVS    3     IND    DC+      Batsman    8781   
64       65         Mishra, A    2     IND    DD+       Bowler     392   
65       66         Mithun, A    1     IND    RCB       Bowler     120   
71       72         Nayar, AM    2     IND    MI+   Allrounder       0   
72       73          Nehra, A    2     IND    DD+       Bowler      77   
75       76          Ojha, NV    2     IND    RR+    W. Keeper       0   
76       77          Ojha, PP    1     IND    DC+       Bowler      70   
78       79      Pankaj Singh    2     IND   RCB+       Bowler       0   
79       80         Patel, MM    2     IND    RR+       Bowler      60   
80       81         Patel, PA    2     IND   CSK+    W. Keeper     683   
81       82        Pathan, IK    2     IND  KXIP+   Allrounder    1105   
82       83        Pathan, YK    2     IND    RR+   Allrounder       0   
87       88         Powar, RR    2     IND  KXIP+       Bowler      13   
88       89         Raina, SK    1     IND    CSK      Batsman     710   
90       91          Saha, WP    2     IND   KKR+    W. Keeper      74   
93       94         Sehwag, V    2     IND     DD      Batsman    8178   
95       96         Sharma, I    1     IND   KKR+       Bowler     432   
96       97         Sharma, J    2     IND    CSK   Allrounder       0   
97       98        Sharma, RG    1     IND    DC+      Batsman       0   
101     102         Singh, RP    2     IND    DC+       Bowler     116   
105     106      Sreesanth, S    2     IND  KXIP+       Bowler     281   
111     112     Tendulkar, SR    3     IND     MI      Batsman   15470   
112     113        Tiwary, MK    2     IND    DD+      Batsman       0   
113     114        Tiwary, SS    1     IND    MI+      Batsman       0   
114     115          Tyagi, S    1     IND    CSK       Bowler       0   
116     117       Uthappa, RV    2     IND   RCB+      Batsman       0   
119     120  Venugopal Rao, Y    2     IND    DC+      Batsman       0   
121     122    Vinay Kumar, R    2     IND   RCB+       Bowler      11   
125     126         Yadav, AS    2     IND     DC      Batsman       0   
127     128      Yuvraj Singh    2     IND  KXIP+      Batsman    1775   
128     129       Zaheer Khan    2     IND    MI+       Bowler    1114   

     T-W

In [55]:
df[df['TEAM'] == "KKR"] # boolean mask

Sl.NO.    PLAYER NAME  AGE COUNTRY TEAM PLAYING ROLE  T-RUNS  T-WKTS  \
2         3    Agarkar, AB    2     IND  KKR       Bowler     571      58   
86       87    Ponting, RT    3     AUS  KKR      Batsman   13218       5   
98       99  Shoaib Akhtar    3     PAK  KKR       Bowler     544     178   
109     110       Taibu, T    2     ZIM  KKR    W. Keeper    1546       1   
115     116       Umar Gul    2     PAK  KKR       Bowler     541     157   

     ODI-RUNS-S  ODI-SR-B  ...  SIXERS  RUNS-C  WKTS  AVE-BL  ECON  SR-BL  \
2          1269     80.62  ...       5    1059    29   36.52  8.81   24.9   
86        13704     80.39  ...       1       0     0    0.00  0.00    0.0   
98          394     73.23  ...       0      54     5   10.80  7.71    8.4   
109        3393     67.58  ...       0       0     0    0.00  0.00    0.0   
115         368     69.04  ...       5     184    12   15.33  8.17   11.2   

     AUCTION YEAR  BASE PRICE  SOLD PRICE  PREMIUM  
2            2008      200000      350000   150000  
86           2008      335000      400000    65000  
98           2008      250000      425000   175000  
109          2008      125000      125000        0  
115          2008      150000      150000        0  

[5 rows x 27 columns]

In [56]:
# more than one condition --> 
cond1 = df['COUNTRY'] == "IND"
cond1

0      False
1      False
2       True
3       True
4       True
       ...  
125     True
126    False
127     True
128     True
129    False
Name: COUNTRY, Length: 130, dtype: bool

In [57]:
cond2 = df["TEAM"] == "KKR"
cond2

0      False
1      False
2       True
3      False
4      False
       ...  
125    False
126    False
127    False
128    False
129    False
Name: TEAM, Length: 130, dtype: bool

In [58]:
cond1 & cond2

0      False
1      False
2       True
3      False
4      False
       ...  
125    False
126    False
127    False
128    False
129    False
Length: 130, dtype: bool

In [59]:
df[cond1 & cond2]

Sl.NO.  PLAYER NAME  AGE COUNTRY TEAM PLAYING ROLE  T-RUNS  T-WKTS  \
2       3  Agarkar, AB    2     IND  KKR       Bowler     571      58   

   ODI-RUNS-S  ODI-SR-B  ...  SIXERS  RUNS-C  WKTS  AVE-BL  ECON  SR-BL  \
2        1269     80.62  ...       5    1059    29   36.52  8.81   24.9   

   AUCTION YEAR  BASE PRICE  SOLD PRICE  PREMIUM  
2          2008      200000      350000   150000  

[1 rows x 27 columns]

In [60]:
df[~(df['COUNTRY'] == "IND")] # invert the selection 

Sl.NO.    PLAYER NAME  AGE COUNTRY  TEAM PLAYING ROLE  T-RUNS  T-WKTS  \
0         1    Abdulla, YA    2      SA  KXIP   Allrounder       0       0   
1         2   Abdur Razzak    2     BAN   RCB       Bowler     214      18   
5         6     Bailey, GJ    2     AUS   CSK      Batsman       0       0   
7         8  Bollinger, DE    2     AUS   CSK       Bowler      54      50   
8         9       Botha, J    2      SA    RR   Allrounder      83      17   
..      ...            ...  ...     ...   ...          ...     ...     ...   
122     123      Warne, SK    3     AUS    RR       Bowler    3154     708   
123     124     Warner, DA    1     AUS    DD      Batsman     483       2   
124     125      White, CL    2     AUS  RCB+      Batsman     146       5   
126     127    Younis Khan    2     PAK    RR      Batsman    6398       7   
129     130     Zoysa, DNT    2      SL    DC       Bowler     288      64   

     ODI-RUNS-S  ODI-SR-B  ...  SIXERS  RUNS-C  WKTS  AVE-BL   ECON  SR-BL  \
0             0      0.00  ...       0     307    15   20.47   8.90  13.93   
1           657     71.41  ...       0      29     0    0.00  14.50   0.00   
5           172     72.26  ...       0       0     0    0.00   0.00   0.00   
7            50     92.59  ...       1     693    37   18.73   7.22  15.57   
8           609     85.77  ...       3     610    19   32.11   6.85  28.11   
..          ...       ...  ...     ...     ...   ...     ...    ...    ...   
122        1018     72.04  ...       6    1447    57   25.39   7.27  20.95   
123         876     85.79  ...      44       0     0    0.00   0.00   0.00   
124        2037     80.48  ...      29      70     0    0.00  14.00   0.00   
126        6814     75.78  ...       0       0     0    0.00   0.00   0.00   
129         343     95.81  ...       0      99     2   49.50   9.00  33.00   

     AUCTION YEAR  BASE PRICE  SOLD PRICE  PREMIUM  
0            2009       50000       50000        0  
1            2008       50000       50000        0  
5            2009       50000       50000        0  
7            2011      200000      700000   500000  
8            2011      200000      950000   750000  
..            ...         ...         ...      ...  
122          2008      450000      450000        0  
123          2011      200000      750000   550000  
124          2008      100000      500000   400000  
126          2008      225000      225000        0  
129          2008      100000      110000    10000  

[77 rows x 27 columns]

In [61]:
df[df['RUNS-C'] > 1500]

Sl.NO.     PLAYER NAME  AGE COUNTRY   TEAM PLAYING ROLE  T-RUNS  T-WKTS  \
12       13      Chawla, PP    1     IND   KXIP   Allrounder       5       3   
44       45      Kallis, JH    3      SA    RCB   Allrounder   12379     276   
51       52        Kumar, P    1     IND   RCB+       Bowler     149      27   
64       65       Mishra, A    2     IND    DD+       Bowler     392      43   
67       68      Morkel, JA    2      SA    CSK   Allrounder      58       1   
76       77        Ojha, PP    1     IND    DC+       Bowler      70      62   
79       80       Patel, MM    2     IND    RR+       Bowler      60      35   
81       82      Pathan, IK    2     IND  KXIP+   Allrounder    1105     100   
101     102       Singh, RP    2     IND    DC+       Bowler     116      40   
121     122  Vinay Kumar, R    2     IND   RCB+       Bowler      11       1   
128     129     Zaheer Khan    2     IND    MI+       Bowler    1114     288   

     ODI-RUNS-S  ODI-SR-B  ...  SIXERS  RUNS-C  WKTS  AVE-BL   ECON   SR-BL  \
12           38     65.51  ...       9    1819    73  126.30  38.11  100.20   
44        11498     72.97  ...      37    1713    45   38.07   7.96   28.71   
51          292     88.21  ...      14    1919    53   36.21   7.73   28.11   
64            5     27.77  ...       3    1530    74   20.68   7.11   17.46   
67          782    100.25  ...      45    1899    69   27.52   8.25   20.01   
76           41     43.61  ...       0    1548    69   22.43   7.16   18.80   
79           74     66.07  ...       0    1504    70   21.49   7.39   17.47   
81         1468     78.96  ...      34    1975    66   29.92   7.74   23.23   
101         104     42.97  ...       1    1892    74   25.57   7.75   19.78   
121          43     43.87  ...       5    1664    61   27.28   8.24   19.87   
128         790     73.55  ...       1    1783    65   27.43   7.75   21.26   

     AUCTION YEAR  BASE PRICE  SOLD PRICE  PREMIUM  
12           2008      125000      400000   275000  
44           2008      225000      900000   675000  
51           2011      200000      800000   600000  
64           2011      100000      300000   200000  
67           2008      225000      675000   450000  
76           2011      200000      500000   300000  
79           2008      100000      275000   175000  
81           2008      200000      925000   725000  
101          2008      200000      875000   675000  
121          2011      100000      475000   375000  
128          2008      200000      450000   250000  

[11 rows x 27 columns]

In [62]:
output = df[df['RUNS-C'] > 1500]
output

Sl.NO.     PLAYER NAME  AGE COUNTRY   TEAM PLAYING ROLE  T-RUNS  T-WKTS  \
12       13      Chawla, PP    1     IND   KXIP   Allrounder       5       3   
44       45      Kallis, JH    3      SA    RCB   Allrounder   12379     276   
51       52        Kumar, P    1     IND   RCB+       Bowler     149      27   
64       65       Mishra, A    2     IND    DD+       Bowler     392      43   
67       68      Morkel, JA    2      SA    CSK   Allrounder      58       1   
76       77        Ojha, PP    1     IND    DC+       Bowler      70      62   
79       80       Patel, MM    2     IND    RR+       Bowler      60      35   
81       82      Pathan, IK    2     IND  KXIP+   Allrounder    1105     100   
101     102       Singh, RP    2     IND    DC+       Bowler     116      40   
121     122  Vinay Kumar, R    2     IND   RCB+       Bowler      11       1   
128     129     Zaheer Khan    2     IND    MI+       Bowler    1114     288   

     ODI-RUNS-S  ODI-SR-B  ...  SIXERS  RUNS-C  WKTS  AVE-BL   ECON   SR-BL  \
12           38     65.51  ...       9    1819    73  126.30  38.11  100.20   
44        11498     72.97  ...      37    1713    45   38.07   7.96   28.71   
51          292     88.21  ...      14    1919    53   36.21   7.73   28.11   
64            5     27.77  ...       3    1530    74   20.68   7.11   17.46   
67          782    100.25  ...      45    1899    69   27.52   8.25   20.01   
76           41     43.61  ...       0    1548    69   22.43   7.16   18.80   
79           74     66.07  ...       0    1504    70   21.49   7.39   17.47   
81         1468     78.96  ...      34    1975    66   29.92   7.74   23.23   
101         104     42.97  ...       1    1892    74   25.57   7.75   19.78   
121          43     43.87  ...       5    1664    61   27.28   8.24   19.87   
128         790     73.55  ...       1    1783    65   27.43   7.75   21.26   

     AUCTION YEAR  BASE PRICE  SOLD PRICE  PREMIUM  
12           2008      125000      400000   275000  
44           2008      225000      900000   675000  
51           2011      200000      800000   600000  
64           2011      100000      300000   200000  
67           2008      225000      675000   450000  
76           2011      200000      500000   300000  
79           2008      100000      275000   175000  
81           2008      200000      925000   725000  
101          2008      200000      875000   675000  
121          2011      100000      475000   375000  
128          2008      200000      450000   250000  

[11 rows x 27 columns]

In [63]:
output.to_csv("output.csv",index=False)

In [64]:
df[~(df['COUNTRY'] == "IND")].head()[["PLAYER NAME","TEAM","COUNTRY"]]

PLAYER NAME  TEAM COUNTRY
0    Abdulla, YA  KXIP      SA
1   Abdur Razzak   RCB     BAN
5     Bailey, GJ   CSK     AUS
7  Bollinger, DE   CSK     AUS
8       Botha, J    RR      SA

# Grouping and Aggregation

In [65]:
df.head()

Sl.NO.   PLAYER NAME  AGE COUNTRY  TEAM PLAYING ROLE  T-RUNS  T-WKTS  \
0       1   Abdulla, YA    2      SA  KXIP   Allrounder       0       0   
1       2  Abdur Razzak    2     BAN   RCB       Bowler     214      18   
2       3   Agarkar, AB    2     IND   KKR       Bowler     571      58   
3       4     Ashwin, R    1     IND   CSK       Bowler     284      31   
4       5  Badrinath, S    2     IND   CSK      Batsman      63       0   

   ODI-RUNS-S  ODI-SR-B  ...  SIXERS  RUNS-C  WKTS  AVE-BL   ECON  SR-BL  \
0           0      0.00  ...       0     307    15   20.47   8.90  13.93   
1         657     71.41  ...       0      29     0    0.00  14.50   0.00   
2        1269     80.62  ...       5    1059    29   36.52   8.81  24.90   
3         241     84.56  ...       0    1125    49   22.96   6.23  22.14   
4          79     45.93  ...      28       0     0    0.00   0.00   0.00   

   AUCTION YEAR  BASE PRICE  SOLD PRICE  PREMIUM  
0          2009       50000       50000        0  
1          2008       50000       50000        0  
2          2008      200000      350000   150000  
3          2011      100000      850000   750000  
4          2011      100000      800000   700000  

[5 rows x 27 columns]

In [68]:
df['TEAM'].unique()

array(['KXIP', 'RCB', 'KKR', 'CSK', 'CSK+', 'RR', 'RCB+', 'MI+', 'DD+',
       'KKR+', 'DC', 'MI', 'DC+', 'RR+', 'KXIP+', 'KXI+', 'DD'],
      dtype=object)

In [ ]:
# Find the Average Selling price of the players per TEAM

In [ ]:
# Apply method

In [73]:
def team_fix(team):
    if team in ["KXIP","KXIP+","KXI+"]:
        return "KXIP"
    if team in ["RCB","RCB+"]:
        return "RCB"
    if team in ["KKR","KKR+"]:
        return "KKR"
    if team in ["CSK","CSK+"]:
        return "CSK"
    if team in ["RR","RR+"]:
        return "RR"
    if team in ["MI","MI+"]:
        return "MI"
    if team in ["DD","DD+"]:
        return "DD"
    if team in ["DC","DC+"]:
        return "DC"

In [74]:
df['NEW_TEAM'] = df['TEAM'].apply(team_fix)

In [75]:
df['NEW_TEAM'].unique()

array(['KXIP', 'RCB', 'KKR', 'CSK', 'RR', 'MI', 'DD', 'DC'], dtype=object)

In [ ]:
#Groupby Function
# Split the data as per the categorical data
# aggregation : sum, max , min, mean, std

In [76]:
df.groupby("NEW_TEAM").mean() 

/var/folders/xk/0pfb24315clcz5hhv8f69q5c0000gp/T/ipykernel_38707/1456102722.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby("NEW_TEAM").mean()


Sl.NO.       AGE       T-RUNS      T-WKTS   ODI-RUNS-S  \
NEW_TEAM                                                              
CSK       45.684211  2.052632  1815.894737   84.473684  2031.052632   
DC        85.411765  2.235294  1781.235294   48.588235  2587.470588   
DD        69.625000  2.062500  1972.375000   77.875000  2194.187500   
KKR       59.176471  2.117647  2123.529412   40.176471  2757.941176   
KXIP      67.307692  2.000000  2652.461538   43.461538  3094.307692   
MI        59.250000  2.166667  2740.000000  129.416667  3548.250000   
RCB       68.714286  2.095238  2870.904762   59.619048  2651.000000   
RR        69.733333  2.000000  1438.733333   61.266667  1539.400000   

           ODI-SR-B    ODI-WKTS  ODI-SR-BL  CAPTAINCY EXP      RUNS-S  ...  \
NEW_TEAM                                                               ...   
CSK       76.648421   71.578947  39.821053       0.263158  514.052632  ...   
DC        73.190588   81.176471  29.123529       0.235294  459.941176  ...   
DD        66.834375   82.562500  30.318750       0.375000  641.000000  ...   
KKR       73.137059   71.647059  40.882353       0.294118  447.058824  ...   
KXIP      61.968462   67.846154  30.238462       0.230769  516.846154  ...   
MI        71.828333  162.166667  30.625000       0.333333  692.916667  ...   
RCB       74.342857   50.428571  35.338095       0.476190  530.428571  ...   
RR        67.293333   48.266667  32.660000       0.266667  349.133333  ...   

             SIXERS      RUNS-C       WKTS     AVE-BL      ECON      SR-BL  \
NEW_TEAM                                                                     
CSK       17.631579  501.000000  18.421053  20.746316  5.044211  15.530526   
DC        19.117647  428.588235  16.352941  22.563529  6.777647  17.036471   
DD        18.125000  397.250000  15.312500  25.611250  6.265000  18.436875   
KKR       19.882353  405.411765  12.705882  24.991765  6.089412  18.597059   
KXIP      16.076923  598.846154  20.000000  27.586154  7.240769  21.280000   
MI        21.500000  643.666667  25.916667  22.200000  7.082500  17.744167   
RCB       16.285714  431.476190  13.095238  24.274762  6.696190  17.090952   
RR        13.533333  479.666667  19.800000  17.142667  4.801333  14.361333   

          AUCTION YEAR     BASE PRICE     SOLD PRICE        PREMIUM  
NEW_TEAM                                                             
CSK        2009.052632  214473.684211  568684.210526  354210.526316  
DC         2008.764706  170588.235294  494705.882353  324117.647059  
DD         2009.125000  205937.500000  578437.500000  372500.000000  
KKR        2009.235294  175588.235294  434705.882353  259117.647059  
KXIP       2008.769231  197692.307692  528461.538462  330769.230769  
MI         2009.333333  200000.000000  693750.000000  493750.000000  
RCB        2009.285714  216428.571429  508809.523810  292380.952381  
RR         2009.133333  148000.000000  401266.666667  253266.666667  

[8 rows x 23 columns]

In [77]:
df.groupby("NEW_TEAM").mean()["SOLD PRICE"]

/var/folders/xk/0pfb24315clcz5hhv8f69q5c0000gp/T/ipykernel_38707/2294191948.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby("NEW_TEAM").mean()["SOLD PRICE"]


NEW_TEAM
CSK     568684.210526
DC      494705.882353
DD      578437.500000
KKR     434705.882353
KXIP    528461.538462
MI      693750.000000
RCB     508809.523810
RR      401266.666667
Name: SOLD PRICE, dtype: float64

In [78]:
df.describe()

Sl.NO.         AGE        T-RUNS      T-WKTS    ODI-RUNS-S  \
count  130.000000  130.000000    130.000000  130.000000    130.000000   
mean    65.500000    2.092308   2166.715385   66.530769   2508.738462   
std     37.671829    0.576627   3305.646757  142.676855   3582.205625   
min      1.000000    1.000000      0.000000    0.000000      0.000000   
25%     33.250000    2.000000     25.500000    0.000000     73.250000   
50%     65.500000    2.000000    542.500000    7.000000    835.000000   
75%     97.750000    2.000000   3002.250000   47.500000   3523.500000   
max    130.000000    3.000000  15470.000000  800.000000  18426.000000   

         ODI-SR-B    ODI-WKTS   ODI-SR-BL  CAPTAINCY EXP       RUNS-S  ...  \
count  130.000000  130.000000  130.000000     130.000000   130.000000  ...   
mean    71.164385   76.076923   34.033846       0.315385   514.246154  ...   
std     25.898440  111.205070   26.751749       0.466466   615.226335  ...   
min      0.000000    0.000000    0.000000       0.000000     0.000000  ...   
25%     65.650000    0.000000    0.000000       0.000000    39.000000  ...   
50%     78.225000   18.500000   36.600000       0.000000   172.000000  ...   
75%     86.790000  106.000000   45.325000       1.000000   925.250000  ...   
max    116.660000  534.000000  150.000000       1.000000  2254.000000  ...   

           SIXERS       RUNS-C        WKTS      AVE-BL        ECON  \
count  130.000000   130.000000  130.000000  130.000000  130.000000   
mean    17.692308   475.523077   17.169231   23.110231    6.204462   
std     23.828146   558.314049   21.816763   20.802057    4.941531   
min      0.000000     0.000000    0.000000    0.000000    0.000000   
25%      1.000000     0.000000    0.000000    0.000000    0.000000   
50%      6.000000   297.000000    8.500000   24.785000    7.380000   
75%     29.750000   689.250000   23.750000   35.580000    8.247500   
max    129.000000  1975.000000   83.000000  126.300000   38.110000   

            SR-BL  AUCTION YEAR    BASE PRICE    SOLD PRICE       PREMIUM  
count  130.000000    130.000000  1.300000e+02  1.300000e+02  1.300000e+02  
mean    17.382615   2009.092308  1.922308e+05  5.212231e+05  3.289923e+05  
std     15.273422      1.377821  1.530973e+05  4.068074e+05  3.517406e+05  
min      0.000000   2008.000000  2.000000e+04  2.000000e+04  0.000000e+00  
25%      0.000000   2008.000000  1.000000e+05  2.250000e+05  5.500000e+03  
50%     19.935000   2008.000000  2.000000e+05  4.375000e+05  2.250000e+05  
75%     26.212500   2011.000000  2.250000e+05  7.000000e+05  5.437500e+05  
max    100.200000   2011.000000  1.350000e+06  1.800000e+06  1.650000e+06  

[8 rows x 23 columns]

In [79]:
# Renaming of columns
df.columns

Index(['Sl.NO.', 'PLAYER NAME', 'AGE', 'COUNTRY', 'TEAM', 'PLAYING ROLE',
       'T-RUNS', 'T-WKTS', 'ODI-RUNS-S', 'ODI-SR-B', 'ODI-WKTS', 'ODI-SR-BL',
       'CAPTAINCY EXP', 'RUNS-S', 'HS', 'AVE', 'SR-B', 'SIXERS', 'RUNS-C',
       'WKTS', 'AVE-BL', 'ECON', 'SR-BL', 'AUCTION YEAR', 'BASE PRICE',
       'SOLD PRICE', 'PREMIUM', 'NEW_TEAM'],
      dtype='object')

In [80]:
df.rename(columns={'Sl.NO.':"Serial No."},inplace=True)

In [81]:
df.head()

Serial No.   PLAYER NAME  AGE COUNTRY  TEAM PLAYING ROLE  T-RUNS  T-WKTS  \
0           1   Abdulla, YA    2      SA  KXIP   Allrounder       0       0   
1           2  Abdur Razzak    2     BAN   RCB       Bowler     214      18   
2           3   Agarkar, AB    2     IND   KKR       Bowler     571      58   
3           4     Ashwin, R    1     IND   CSK       Bowler     284      31   
4           5  Badrinath, S    2     IND   CSK      Batsman      63       0   

   ODI-RUNS-S  ODI-SR-B  ...  RUNS-C  WKTS  AVE-BL   ECON  SR-BL  \
0           0      0.00  ...     307    15   20.47   8.90  13.93   
1         657     71.41  ...      29     0    0.00  14.50   0.00   
2        1269     80.62  ...    1059    29   36.52   8.81  24.90   
3         241     84.56  ...    1125    49   22.96   6.23  22.14   
4          79     45.93  ...       0     0    0.00   0.00   0.00   

   AUCTION YEAR  BASE PRICE  SOLD PRICE  PREMIUM  NEW_TEAM  
0          2009       50000       50000        0      KXIP  
1          2008       50000       50000        0       RCB  
2          2008      200000      350000   150000       KKR  
3          2011      100000      850000   750000       CSK  
4          2011      100000      800000   700000       CSK  

[5 rows x 28 columns]

In [82]:
#missing values
df.isna() 
# imputation - filling the missing values with statiscally correct values
# numerical columns --> mean/median
# string columns --> mode

Serial No.  PLAYER NAME    AGE  COUNTRY   TEAM  PLAYING ROLE  T-RUNS  \
0         False        False  False    False  False         False   False   
1         False        False  False    False  False         False   False   
2         False        False  False    False  False         False   False   
3         False        False  False    False  False         False   False   
4         False        False  False    False  False         False   False   
..          ...          ...    ...      ...    ...           ...     ...   
125       False        False  False    False  False         False   False   
126       False        False  False    False  False         False   False   
127       False        False  False    False  False         False   False   
128       False        False  False    False  False         False   False   
129       False        False  False    False  False         False   False   

     T-WKTS  ODI-RUNS-S  ODI-SR-B  ...  RUNS-C   WKTS  AVE-BL   ECON  SR-BL  \
0     False       False     False  ...   False  False   False  False  False   
1     False       False     False  ...   False  False   False  False  False   
2     False       False     False  ...   False  False   False  False  False   
3     False       False     False  ...   False  False   False  False  False   
4     False       False     False  ...   False  False   False  False  False   
..      ...         ...       ...  ...     ...    ...     ...    ...    ...   
125   False       False     False  ...   False  False   False  False  False   
126   False       False     False  ...   False  False   False  False  False   
127   False       False     False  ...   False  False   False  False  False   
128   False       False     False  ...   False  False   False  False  False   
129   False       False     False  ...   False  False   False  False  False   

     AUCTION YEAR  BASE PRICE  SOLD PRICE  PREMIUM  NEW_TEAM  
0           False       False       False    False     False  
1           False       False       False    False     False  
2           False       False       False    False     False  
3           False       False       False    False     False  
4           False       False       False    False     False  
..            ...         ...         ...      ...       ...  
125         False       False       False    False     False  
126         False       False       False    False     False  
127         False       False       False    False     False  
128         False       False       False    False     False  
129         False       False       False    False     False  

[130 rows x 28 columns]

In [83]:
df.isna().sum()

Serial No.       0
PLAYER NAME      0
AGE              0
COUNTRY          0
TEAM             0
PLAYING ROLE     0
T-RUNS           0
T-WKTS           0
ODI-RUNS-S       0
ODI-SR-B         0
ODI-WKTS         0
ODI-SR-BL        0
CAPTAINCY EXP    0
RUNS-S           0
HS               0
AVE              0
SR-B             0
SIXERS           0
RUNS-C           0
WKTS             0
AVE-BL           0
ECON             0
SR-BL            0
AUCTION YEAR     0
BASE PRICE       0
SOLD PRICE       0
PREMIUM          0
NEW_TEAM         0
dtype: int64

In [91]:
loan_df = pd.read_csv("https://raw.githubusercontent.com/manifoldailearning/Complete-MLOps-BootCamp/main/Packaging-ML-Model/Experiments/train.csv")

In [92]:
loan_df.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [94]:
loan_df.isna().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [95]:
loan_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [97]:
loan_df['Gender'].mode()[0] # most frequently occuring value

'Male'

In [98]:
loan_df['Gender'] = loan_df['Gender'].fillna(loan_df['Gender'].mode()[0])

In [99]:
loan_df.isna().sum()

Loan_ID               0
Gender                0
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [100]:
loan_df['LoanAmount'].mean()

146.41216216216216

In [101]:
loan_df['LoanAmount'] = loan_df['LoanAmount'].fillna(loan_df['LoanAmount'].mean())

In [ ]:
# numerical - mean
# categorical - mode