In [1]:
l1 = [10,20,30]
l2 = [30,40,50]
l1+l2

[10, 20, 30, 30, 40, 50]

In [2]:
# memory 
import numpy as np

In [25]:
l1 = [1,2,3]
x = np.array(object=l1)
print(x)

[1 2 3]


In [4]:
type(x)

numpy.ndarray

In [5]:
x = np.array(object=[[1,2,3],[23,4,5]])
print(x)

[[ 1  2  3]
 [23  4  5]]


In [6]:
x[1,1] # indexing

4

In [7]:
# metadata/attribute
x.shape # returns the shape of an array

(2, 3)

In [8]:
x.dtype # data type of an array

dtype('int64')

In [10]:
x.ndim # number of dimensions of an array

2

In [9]:
x = np.array(object=[[1,2,3],[23,"4","5"]])
print(x) # all the values will be converted to string

[['1' '2' '3']
 ['23' '4' '5']]


int < float < complex < str

In [11]:
np.arange(10, 20) # return the values filled between start and stop
# start is included, stop is excluded

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [12]:
np.zeros(shape=(4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones(shape=(4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.linspace(start=1,stop=5,num=10) # generate the array with required equidistant elements from start to stop

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [16]:
arr = np.linspace(start=1,stop=5,num=10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [17]:
arr.shape # metadata / attribute

(10,)

In [18]:
arr.ndim

1

In [19]:
arr1 = arr.reshape(2,5)

In [20]:
arr1

array([[1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778],
       [3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ]])

In [21]:
arr1.shape

(2, 5)

In [22]:
arr1 + arr1

array([[ 2.        ,  2.88888889,  3.77777778,  4.66666667,  5.55555556],
       [ 6.44444444,  7.33333333,  8.22222222,  9.11111111, 10.        ]])

In [23]:
arr1 * arr1

array([[ 1.        ,  2.08641975,  3.56790123,  5.44444444,  7.71604938],
       [10.38271605, 13.44444444, 16.90123457, 20.75308642, 25.        ]])

In [24]:
arr1 / arr1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
x = np.ones(shape=(2,3,4))

In [30]:
x.dtype

dtype('float64')

In [27]:
x = np.array(['a','b'])

In [28]:
x*x

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U1'), dtype('<U1')) -> None

In [38]:
l2 = [20.2, 35.6, 45.98, 50.25]
x = np.array(l2, dtype='int') # no rounding
x

array([20, 35, 45, 50])

In [39]:
#64 bit data is used
x.dtype

dtype('int64')

In [34]:
x = np.array(l2, dtype=np.int8) # no rounding
x

array([20, 35, 45, 50], dtype=int8)

In [35]:
x[0] = "hello"

ValueError: invalid literal for int() with base 10: 'hello'

In [36]:
x[0] = 12.25

In [37]:
x

array([12, 35, 45, 50], dtype=int8)

In [40]:
np.ones(shape=(2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [41]:
# Indexing & Slicing

In [42]:
# random module
x = np.random.randint(low=10,high=100,size=(4,3)) # numpy array filled with random integers with mentioned range and shape
x

array([[90, 60, 85],
       [48, 65, 17],
       [24, 75, 95],
       [64, 82, 41]])

In [43]:
#indexing
x[2,2]

95

In [44]:
# Slicing
# start is included and stop is excluded
x = np.random.randint(low=10,high=100,size=(6,7)) # numpy array filled with random integers with mentioned range and shape
x

array([[30, 38, 92, 14, 47, 21, 14],
       [35, 25, 27, 44, 91, 81, 81],
       [94, 25, 65, 36, 19, 45, 21],
       [41, 75, 51, 26, 72, 71, 99],
       [91, 57, 20, 39, 70, 36, 14],
       [22, 34, 86, 93, 83, 23, 34]])

In [48]:
x[3:5,5:7]

array([[71, 99],
       [36, 14]])

In [51]:
x[5,10]

IndexError: index 10 is out of bounds for axis 1 with size 7

In [50]:
x[3:5,5:10] # no error

array([[71, 99],
       [36, 14]])

In [49]:
x[3:5,5:]

array([[71, 99],
       [36, 14]])

In [47]:
x[2:5,1:3]

array([[25, 65],
       [75, 51],
       [57, 20]])

In [45]:
x[2:5]

array([[94, 25, 65, 36, 19, 45, 21],
       [41, 75, 51, 26, 72, 71, 99],
       [91, 57, 20, 39, 70, 36, 14]])

In [46]:
x[2:5,2:5]

array([[65, 36, 19],
       [51, 26, 72],
       [20, 39, 70]])