In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/nachikethmurthy/Source-Code-Dataset-for-Machine-Learning-using-Python/main/data.csv")

In [3]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [4]:
# drop the unnecessary columns
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [6]:
#target --> diagnosis
# separate input and output
X = df.drop(columns='diagnosis')
y = df['diagnosis']

y = y.map({"M":0,"B":1}) # manual method for custom encoding

from sklearn.preprocessing import StandardScaler
ss = StandardScaler()

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3, random_state=0)

X_train_transform = ss.fit_transform(X_train) 
X_test_transform = ss.transform(X_test) # 

In [12]:
X_test.iloc[0]# (13.4 - 15.25)/(3.5)

radius_mean                 13.400000
texture_mean                20.520000
perimeter_mean              88.640000
area_mean                  556.700000
smoothness_mean              0.110600
compactness_mean             0.146900
concavity_mean               0.144500
concave points_mean          0.081720
symmetry_mean                0.211600
fractal_dimension_mean       0.073250
radius_se                    0.390600
texture_se                   0.930600
perimeter_se                 3.093000
area_se                     33.670000
smoothness_se                0.005414
compactness_se               0.022650
concavity_se                 0.034520
concave points_se            0.013340
symmetry_se                  0.017050
fractal_dimension_se         0.004005
radius_worst                16.410000
texture_worst               29.660000
perimeter_worst            113.300000
area_worst                 844.400000
smoothness_worst             0.157400
compactness_worst            0.385600
concavity_wo

In [13]:
X_test_transform[0]

array([-0.21855296,  0.31710749, -0.14938447, -0.2872433 ,  1.01628935,
        0.8401481 ,  0.71366732,  0.82317615,  1.10278606,  1.54738509,
       -0.06299909, -0.49676845,  0.10742881, -0.15500641, -0.54923334,
       -0.14567981,  0.11542304,  0.28378104, -0.41028206,  0.10246308,
        0.01015933,  0.67193047,  0.16166188, -0.08348148,  1.08320449,
        0.86166719,  1.25420187,  1.36998461,  1.0939611 ,  1.51560644])

In [8]:
naive_bayes = GaussianNB()
naive_bayes.fit(X_train_transform,y_train)

GaussianNB()

In [9]:
y_pred = naive_bayes.predict(X_test_transform)

from sklearn.metrics import f1_score

f1_score(y_test,y_pred)

0.9295774647887323

In [10]:
y_pred[:5]

array([0, 1, 1, 1, 1])

In [11]:
naive_bayes.predict_proba(X_test_transform)

array([[1.00000000e+000, 8.24471960e-012],
       [6.96416117e-015, 1.00000000e+000],
       [8.63559141e-016, 1.00000000e+000],
       [3.66233354e-014, 1.00000000e+000],
       [8.77805866e-018, 1.00000000e+000],
       [5.87157840e-015, 1.00000000e+000],
       [8.09635031e-012, 1.00000000e+000],
       [1.68297669e-016, 1.00000000e+000],
       [1.60377721e-016, 1.00000000e+000],
       [6.81197194e-019, 1.00000000e+000],
       [9.99999998e-001, 1.82508294e-009],
       [1.37652426e-010, 1.00000000e+000],
       [4.25555394e-016, 1.00000000e+000],
       [9.36138553e-001, 6.38614466e-002],
       [9.99405963e-001, 5.94036554e-004],
       [1.00000000e+000, 6.83686837e-022],
       [9.98208056e-001, 1.79194425e-003],
       [1.00000000e+000, 3.39588430e-058],
       [1.00000000e+000, 6.90231228e-044],
       [1.00000000e+000, 8.87258427e-130],
       [1.00000000e+000, 7.46608657e-020],
       [1.00000000e+000, 6.11177981e-020],
       [1.06057189e-009, 9.99999999e-001],
       [7.3